### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by ddbeck**
As suggested in issue #16 , this adds a license file (and updates the readme file, too). I wasn't sure who the named copyright holder should be, so I put down "Maptime"—happy to change that as needed. Thanks!

### CODE REVIEW

**Comment by geobrando** [comment]
Thanks, @ddbeck.

**Comment by tristen** [comment]
@ddbeck sweet! The actual copyright holder name should be `Time for Maps` as that's the official name.

**Comment by ddbeck** [comment]
@tristen Fixed! Thank you!

**Comment by tristen** [comment]
Woot!

**Pull request merged**
